### ISSUE TITLE
Advice for credentials storage

### ISSUE THREAD

**Issue by sylvainschmitt** [sylvainschmitt/DownClim#3]
Hello @thomasarsouze ,

I'm using `pyesgf.logon` to connect to esgf nodes and retrieve projections, which is working very well. However to use it, I need to pass user credentials to the function. In this case the openid and the password:
```
from pyesgf.logon import LogonManager
lm = LogonManager()
lm.logon_with_openid(openid='https://esgf-node.ipsl.upmc.fr/esgf-idp/openid/sschmitt', password="pwd", interactive=False)
```
Do you have any advice on the best practice to stock this credentials? I was planning on adding a new key pointing to esgf credentials in the [configuration file](https://github.com/sylvainschmitt/DownClim/blob/dev/config/config_dag.yml). And then the user have to simply write the file with yaml keys openid and password to be read by the python script. I will obviously make `git` ignore this credential file. This is the simplest way I imagine it, but maybe this is not secure enough?

Thanks in advance,

_Sylvain_

**Comment by thomasarsouze** [comment]
Never have been in such a case...
It seems that [git-credential is your friend here](https://git-scm.com/docs/gitcredentials)
